// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:279443633621:web:fc507fd6e4978f8fcab95c',
    messagingSenderId: '279443633621',
    projectId: 'ganesh-app-744b5',
    authDomain: 'ganesh-app-744b5.firebaseapp.com',
    storageBucket: 'ganesh-app-744b5.appspot.com',
    measurementId: 'G-7S65ZTG4KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:279443633621:android:9d7efd6eb396c6f4cab95c',
    messagingSenderId: '279443633621',
    projectId: 'ganesh-app-744b5',
    storageBucket: 'ganesh-app-744b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:279443633621:ios:e75c910b053c4cb6cab95c',
    messagingSenderId: '279443633621',
    projectId: 'ganesh-app-744b5',
    storageBucket: 'ganesh-app-744b5.appspot.com',
    iosBundleId: 'com.example.ganpatibapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:279443633621:ios:e75c910b053c4cb6cab95c',
    messagingSenderId: '279443633621',
    projectId: 'ganesh-app-744b5',
    storageBucket: 'ganesh-app-744b5.appspot.com',
    iosBundleId: 'com.example.ganpatibapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:279443633621:web:caf7e1c8d5283fa6cab95c',
    messagingSenderId: '279443633621',
    projectId: 'ganesh-app-744b5',
    authDomain: 'ganesh-app-744b5.firebaseapp.com',
    storageBucket: 'ganesh-app-744b5.appspot.com',
    measurementId: 'G-ZJ9G4G2BGG',
  );
}
